import unittest
from io import StringIO

from sample_registry.illumina import (
    parse_illumina_fastq_header, parse_illumina_folder_date,
)


class IlluminaTests(unittest.TestCase):
    def test_parse_illumina_fastq_header(self):
        f = StringIO(
            u"@D00727:21:C8LJ2ANXX:8:2209:1084:2044 1:N:0:NNNNNNNN+NNNNNNNN")
        expected = {
            "instrument": "D00727",
            "run_number": "21",
            "flowcell_id": "C8LJ2ANXX",
            "lane": "8",
            "read": "1",
            "is_filtered": "N",
            "control_number": "0",
            "index_reads": "NNNNNNNN+NNNNNNNN",
            }
        self.assertEqual(parse_illumina_fastq_header(f), expected)

    def test_parse_illumina_fastq_header_error(self):
        self.assertRaises(
            ValueError, parse_illumina_fastq_header, StringIO(u"abc"))
        
    def test_parse_illumina_folder_date(self):
        path = (
            "Miseq/160511_M03543_0047_000000000-APE6Y/Data/Intensities/"
            "BaseCalls/Undetermined_S0_L001_R1_001.fastq.gz"
        )
        self.assertEqual(parse_illumina_folder_date(path), "2016-05-11")


R1_FASTQ = u"""\
@D00728:20:C8DEKANXX:1:1107:1197:2118 1:N:0:GTAGAGGA+AAGGAGTA
NATATCAGCTGGTATGATTTCACAAAAGAAATCTTCCGTCAGGCCGCTGCCATGGGACACCCGGAATATCTCCCGGAAAACATGACAGTCAACTCCGTCACAACTGCAGAGTATGGCGCTTCCAAA
+
#<<>0EFGCGGEGGGGFGGGGGGGGGGGGGGGGGGGGGGGG>EBGGGGG@GGGGGEGGGG@GGGG<GGG@GCGBGG/CGGGGGG>GGGGFGEGGDGGEGGGGGGGGGG=0@CBD=CDG<>8@GGGG
@D00728:20:C8DEKANXX:1:1107:1160:2123 1:N:0:TCCTGAGC+CTACGCCT
NTATTAACTCGGCTTTATCAAATTCTTTCTTATTCTTCATCACAGCTCCAACAAATCGCTCTATCATTGTTTTGTCTAATTCTATTTCTCTACCCAAATTAAATAAACCAACAGCTGTCTCTTATA
+
#=<<>>1FEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGBGGGGGG>GGGGG>GGFGGGGGGGGGGGF
@D00728:20:C8DEKANXX:1:1107:1236:2146 1:N:0:ATCTCAGG+TATCCTCT
CGTTGATTCTTAGATGCACATGTAAGATACCACAGATACTTTTTAGATTATTCCTGTCTCTTATACACATCTCCGAGCCCACGAGACATCGCAGGTTCTCGTATGCCGTCTTCTGCTTGAAAAAAA
+
@BBBC>GGGFGEF@EFGGGFGGGGGGFDGGGGG@GCG@GEFFGGGFFGDGGGGFGGGGEGGG>FGDGGGGCFGGGGGGG@>GG/E=ECFG/=/=C00?<EGG.FGGGGGGGGGGGGG0<0:6D-,,
@D00728:20:C8DEKANXX:1:1107:1048:2153 1:N:0:ATCTCAGG+GTAAGNGG
GTTGAAATCGTTGCCATTGATTGTTCCACTGGTTTTGTAACTGTCGTTTCCACAGTCTCCGGAGCTGTCTCTTATACACATCTCCGAGCCCACGAGACATCTCAGGATCTCGTATGCCGTCTTCTG
+
3=@BBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGG@GFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG<>CDFGGGGGGGG0CFFGG<GG=CGGDGGGG.
"""

R2_FASTQ = u"""\
@D00728:20:C8DEKANXX:1:1107:1197:2118 2:N:0:GTAGAGGA+AAGGAGTA
TACCTTATGTATTCTGCTTCAATCCGGCAATGCTGCTGATCGATACCACACCACTTAAGGTTGTTCAGATCTTTATCACCTCACTGATTGGTGTGTTTGGATTGTCCTCCTCACTGGAAGGCTTCT
+
BBBCBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGCGGGGGGEGGGGGGGGFGGFGGGBFFBFGGGGGGGGGGGGGBCF@F-8FFDGGGG/
@D00728:20:C8DEKANXX:1:1107:1160:2123 2:N:0:TCCTGAGC+CTACGCCT
CTGTTGGTTTATTTAATTTGGGTAGAGAAATAGAATTAGACAAAACAATGATAGAGCGATTTGTTGGAGCTGTGATGAAGAATAAGAAAGAATTTGATAAAGCCGAGTTAATATCTGTCTCTTATA
+
CCCCCGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGB@G:FGCGGGGEGGGCEECCG/
@D00728:20:C8DEKANXX:1:1107:1236:2146 2:N:0:ATCTCAGG+TATCCTCT
GAATAATCTAAAAAGTATCTGTGGTATCTTACATGTGCATCTAAGAATCAACGCTGTCTCTTATACACATCTGACGCTGCCGACGAAGAGGATAGTGTAGATCTCGGTGGTCGCCGTATCATTAAA
+
CCCCCGGGGGGGGEFEFGGGFFGGGGFGFGGGGGFDGGGGGFBCF1C@FGGGFGGGFFGEFDGGGGGGGCGGGFGGGGG<GG/EC9EG>GGG>?CFFDFGG/D@>FG>FG5FG@DG,,--EE.BG.
@D00728:20:C8DEKANXX:1:1107:1048:2153 2:N:0:ATCTCAGG+GTAAGNGG
NTNCGGAGACTGTGGAAACGACAGTTACAAAACCAGTGGAACAATCAATGGCAACGATTTCAAACTGTCTCTTATACACATCTGACGCTGCCGACGACTCCTTACGTGTAGATCTCGGTGGTCGCC
+
#=#==FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGFGGGBGGBGGBGGGGEGD:
"""
